# Generated by Django 2.2.7 on 2020-01-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Designerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutiquename', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='DesginerWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.FileField(upload_to='images/')),
                ('work_title', models.CharField(max_length=25)),
                ('work_desc', models.TextField()),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Designerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DesginerFabrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=25)),
                ('fabric_desc', models.TextField()),
                ('fabric_cost', models.CharField(max_length=10)),
                ('fabric_image', models.FileField(upload_to='images/')),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Designerdetails')),
            ],
        ),
    ]
