# Generated by Django 2.2.7 on 2019-12-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesginerWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.FileField(upload_to='images/')),
                ('work_title', models.CharField(max_length=25)),
                ('work_desc', models.TextField()),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Designerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DesginerFabrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=25)),
                ('fabric_desc', models.TextField()),
                ('fabric_cost', models.CharField(max_length=10)),
                ('fabric_image', models.FileField(upload_to='images/')),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadapp.Designerdetails')),
            ],
        ),
    ]
